// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpyvikgtvnmzaeiapzar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndweXZpa2d0dm5temFlaWFwemFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NjM3ODksImV4cCI6MjA2MzUzOTc4OX0.Rap5dukBgdk_dD_x4hHrk59Z0IjpHVN5nghPxrRcwTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);